data_config:
  blog-tags: true

collections_config:
  pages:
    icon: wysiwyg
    disable_add_folder: true
    output: true
    path: content
    schemas:
      default:
        path: schemas/page.html
    _enabled_editors:
      - visual
  articles:
    icon: article
    path: content/blog
    disable_add_folder: true
    preview:
      subtext:
        - template: '{"Draft"|if=draft}'
        - template: '{date|date_long}'
        - key: url
      image:
        - key: thumbImg.image_path
      metadata:
        - icon: person
          text:
            - key: author
    schemas:
      default:
        path: schemas/post.md
    _enabled_editors:
      - content
      - visual
  data:
    output: false
    path: data
    icon: settings
    disable_add: true
    disable_add_folder: true
    _enabled_editors:
      - data

paths:
  uploads: static/images

_inputs:
  content:
    type: markdown
  icon:
    type: select
    options:
      values:
        - ph-user-square
  description:
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      removeformat: true
  isActive:
    type: switch
  social[*].icon:
    type: select
    options:
      values:
        - ph-facebook-logo
        - ph-instagram-logo
        - ph-twitter-logo
        - ph-github-logo
        - ph-youtube-logo
  page_description:
    comment: If empty, defaults to the description set in the Site SEO data file
    type: text
  canonical_url:
    comment: If empty, defaults to the URL of the page
    type: text
  featured_image:
    comment: If empty, defaults to the image set in the Site SEO data file
  thumb_image.image:
    type: image
    options:
      width: 500
      height: 413
      resize_style: crop
  author_twitter_handle:
    type: twitter
    comment: Defaults to the twitter site value set in the Site SEO data file
  no_index:
    type: checkbox
    comment: When selected this removes the page from your sitemap and adds the noindex robots meta tag
  open_graph_type:
    type: select
    options:
      values:
        - website
        - article
        - profile
  favicon_icon:
    type: image
    comment: For the shortcut icon meta tag
  favicon_image:
    type: image
    comment: For the icon meta tag
  enable_dropdown:
    type: switch
  dropdown:
    type: array
    options:
      structures: _structures.dropdown
    label: Dropdown Items
    hidden: "!enable_dropdown"
  dropdown_link:
    type: url
    label: Link
  dropdown_text:
    type: text
    label: Name
  items:
    type: array
    options:
      structures: _structures.items
  logo:
    type: image
  categories:
    type: multiselect
    options:
      values: data.blog-tags
  twitter_site:
    type: twitter
    label: Twitter Username
  logo_url:
      comment: Link for the logo in the top left of the footer
  copyright:
    comment: Automatically prefixed with the current year
  enable_nav_btn:
    label: Enable Navigation Button
    type: switch
  nav_btn:
    label: Navigation Button
    hidden: "!enable_nav_btn"
  thumbImg:
    label: Thumbnail Image
  featuredImg:
    label: Featured Image
  image_alt:
    label: Image Description

_structures:
  content_blocks:
    style: modal
  dropdown:
    values:
      - value:
          dropdown_text:
          dropdown_link:
  social:
    values:
      - value:
          link:
          icon:
  sections:
    values:
      - value:
          title:
          links:
  links:
    values:
      - value:
          link:
          text:
  features:
    values:
      - value:
          item:
          isActive:
  items:
    values:
      - value:
          link:
          text:
          enable_dropdown:
          dropdown:
